import type { Metadata } from 'next';
import { Roboto, Roboto_Mono } from 'next/font/google';
import '../styles/index.scss';

const roboto = Roboto({
    variable: '--font-roboto',
    weight: '400',
    subsets: ['latin'],
});
const robotoMono = Roboto_Mono({
    variable: '--font-roboto-mono',
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.variable} ${robotoMono.variable}`}>
                <header>
                    <h2 className="app-header">My Blog</h2>
                </header>
                {children}
            </body>
        </html>
    );
}
